import json
import random
import smtplib
from email.utils import parseaddr
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart


def generate_pairs(count):
    """
    Algorithm to generate pairs.
    Repeatedly generates a list of random numbers between 0 to count and
    ensures that the index is not the same as the generated number.
    """
    while True:
        nums = random.sample(range(count), count)
        if all(i != nums[i] for i in range(count)):
            return nums


def print_pairs(pairs):
     # For debugging purposes only
     for person, partner in pairs.items():
            print(f"{person: <8}:  {partner}")


def send_email(pairs, sender_email, sender_password, player_email_map, email_subject, email_msg):
    """
    Sends an email to each person with their corresponding parter.
    NOTE: This funciton currently assumes that sender email will be using gmail. (uses smtp.gmail.com)
    Arguments:
    pairs - pair of person names
    sender_email - email that will be used to send the email to each person
    sender_password - not the actual user's password. this is the password generated by the email provider (eg. gmail)
    player_email_map - email address of each person
    email_subject - subject of the email (e.g. 2025 Exchange Gift)
    email_msg - additional email msg appended in the email body
    """
    fromaddr = sender_email
    updated_email_msg = email_msg.replace('\n', '<br>')
    for person, partner in pairs.items(): 
        toaddr = player_email_map[person]
        
        msg = MIMEMultipart("related")
        msg['From'] = fromaddr
        msg['To'] = toaddr
        msg['Subject'] = email_subject

        msg_alt = MIMEMultipart("alternative")
        msg.attach(msg_alt)

        partner_display = ""
        try:
            with open(f"{partner}.jpg", "rb") as img_file:
                img = MIMEImage(img_file.read())
                img.add_header('Content-ID', '<image1>')
                img.add_header('Content-Disposition', 'inline', filename='image.jpg')
                msg.attach(img)
                partner_display = '<img id="myImage" src="cid:image1" alt="Embedded Image" style="padding: 30px; width: 1200px; height: auto;">'
        except IOError:
            print(f"WARN: image not found for {partner}, using actual name instead.")
            partner_display = f'<h1>{partner}</h1>'
        

        body_text = f"""\
        <html>
            <body>
                <h1>Hello {person}! 2025 na and it's time for our yearly exchange gift!</h1>
                <h3>{updated_email_msg}</h3>
                <h1>And your partner is...</h1>
                <div style="text-align:center;padding-top: 60px;">
                    {partner_display}
                </div>
            </body>
        </html>
        """
        msg_alt.attach(MIMEText(body_text, 'html'))

        login_user = sender_email.split("@")[0]
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.ehlo()
        server.starttls()
        server.ehlo()
        server.login(login_user, sender_password)
        text = msg.as_string()
        server.sendmail(fromaddr, toaddr, text)
        server.close()


def validate_json_data(json_data: dict):
    """
    Validates the json fields.
    1. Checks if all required fields are present
    2. Checks email addresses
    3. Checks if player count and list of players matches
    """
    fields = ["sender_email", "sender_password", "player_count", "players", "email_subject", "email_msg"]
    for field in fields:
        if field not in json_data:
            print(f"ERROR: JSON file must contain '{field}'")
            exit(1)
    
    if "@" not in parseaddr(json_data["sender_email"])[1]:
            print(f"ERROR: email address: {json_data['sender_email']} is not valid.")
            exit(1)

    player_count = json_data['player_count']
    player_details = json_data['players']
    if len(player_details) != player_count:
        print(f"ERROR: Invalid JSON file: players should have length of player_count ({player_count})")
        exit(1)
    for player_info in player_details:
        if "name" not in player_info or "email" not in player_info:
            print(f"ERROR: each person must have a name and email address")
            exit(1)
        if "@" not in parseaddr(player_info["email"])[1]:
            print(f"ERROR: email address: {player_info['email']} is not valid.")
            exit(1)


if __name__ == "__main__":
    json_file = input("Enter JSON file: ")
    try:
        with open(json_file, "r") as f:
            json_data = json.load(f)
    except IOError:
        print(f"ERROR: {json_file} does not exist!")
        exit(1)
    
    validate_json_data(json_data)
    sender_email = json_data['sender_email']
    sender_password = json_data['sender_password']
    num_players = json_data['player_count']
    players = json_data['players']
    email_subject = json_data['email_subject']
    email_msg = json_data['email_msg']
    names = [item['name'] for item in players]
    player_email_map = {item['name'] : item['email'] for item in players}
    
    partners = generate_pairs(num_players)
    pairs = {names[i] : names[partners[i]] for i in range(num_players)}

    send_email(pairs, sender_email, sender_password, player_email_map, email_subject, email_msg)
